# Generated by Django 4.0.3 on 2022-04-28 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0010_membership_membershiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='initial',
            field=models.DateField(default=datetime.date(2022, 4, 28)),
        ),
    ]
